name: Generate SoundOntology documentation
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'ontology/SoundOntologyV3.owl'
env:
  ONTOLOGY_FILE: ontology/SoundOntologyV3.owl
  # ONTOLOGY_FILE: ontology/sio.owl
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/vemonet/Ontospy@improve-labels
        pip install Django>=1.10.3 Pygments==2.1.3
        wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.15/widoco-1.4.15-jar-with-dependencies.jar
        mkdir -p docs/browse docs/tree docs/graph docs/lode
    - name: Generate docs with Widoco (LODE)
      run: |
        java -jar widoco.jar -ontFile $ONTOLOGY_FILE -outFolder docs/lode/ -getOntologyMetadata -oops -rewriteAll -webVowl
    - name: Generate docs with Ontospy
      run: |
        ontospy gendocs -o docs/browse --type 2 --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o docs/tree --type 4 --nobrowser $ONTOLOGY_FILE
        ontospy gendocs -o docs/graph --type 10 --nobrowser $ONTOLOGY_FILE
    - name: Commit and push
      run: |
        git config --global user.name 'Martin Bremm'
        git config --global user.email 'm.bremm@student.maastrichtuniversity.nl'
        git fetch
        git checkout gh-pages
        rm -rf browse tree graph lode
        mv docs/* .
        git add browse graph lode tree
        git commit -m "Automatically generate documentation from SoundOntology OWL ontology file using Ontospy and Widoco (lode)."
        git push || exit 0
    
    # - name: Hotfix graph nodes sizes in ontospy docs
    #   run: |
    #     find docs/graph/index.html -type f -exec sed -i "s/minNodeSize: 1,/minNodeSize: 2,/g" {} +
    #     find docs/graph/index.html -type f -exec sed -i "s/maxNodeSize: 30,/maxNodeSize: 24,/g" {} +
